# enter number of proficiencies - 0 for none, 1 for single, 2 for double, ...
prf = {
    "initiative": 0,
    "str_save": 0,
    "dex_save": 0,
    "con_save": 0,
    "int_save": 0,
    "wis_save": 0,
    "cha_save": 0,
    "acrobatics": 0,
    "animal_handling": 0,
    "arcana": 0,
    "athletics": 0,
    "deception": 0,
    "history": 0,
    "insight": 0,
    "intimidation": 0,
    "investigation": 0,
    "medicine": 0,
    "nature": 0,
    "perception": 0,
    "performance": 0,
    "persuasion": 0,
    "religion": 0,
    "sleight_of_hand": 0,
    "stealth": 0,
    "survival": 0,
    "pas_perception": 0,
    "pas_investigation": 0,
    "pas_insight": 0
}